package:
  name: pyplumb
  version: "0.1.0"
 
source:
  git_rev: master
  git_url: https://github.com/jadudm/pyplumb.git
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
 
about:
  home: http://concurrency.cc/
  license: MIT
  license_file: LICENSE
	summary: A tool for writing occam programs for the Arduino.
